Repository limitless-labs-group/Limitless-Exchange, pull requests merged in 2024-04, with the labels that each got.

#7 Introduce "share on Farcaster" feature
  .gitattributes
  public/assets/images/farcaster.png
  src/app/markets/[address]/components/MarketMetadata.tsx
  src/app/portfolio/components/PortfolioMarketCard.tsx
  src/components/markets/MarketCard.tsx
  src/services/ShareService.tsx
  src/services/index.ts
Labels: enhancement

#5 fix/events not properly tracked
  src/app/markets/[address]/components/TradeForm.tsx
  src/app/page.tsx
  src/app/portfolio/components/PortfolioStats.tsx
  src/app/portfolio/page.tsx
  src/app/wallet/components/DepositByQrCard.tsx
  src/app/wallet/page.tsx
  src/components/layouts/Header.tsx
  src/components/layouts/HeaderProfileMenuDesktop.tsx
  src/components/layouts/HeaderProfileMenuMobile.tsx
  src/components/markets/CreateMarketCard.tsx
  src/components/markets/MarketCard.tsx
  src/services/Amplitude.tsx
Labels: bug, enhancement

#8 Introduce the PriceOracleProvider
  src/app/providers.tsx
  src/providers/PriceOracle.tsx
  src/providers/index.ts
  src/utils/Coingecko.ts
  src/utils/index.ts
Labels: enhancement

#9 Add FAQ button to footer component
  src/app/page.tsx
  src/components/layouts/Footer.tsx
Labels: enhancement

#12 fix: fix the ethers -> ether typo in the hint tooltip
  src/app/wallet/components/WithdrawModal.tsx
Labels: bug
